import type { AdminCustomerRow, AdminOrderRow, AdminProductRow } from "./list-types";

export const MOCK_ADMIN_ORDERS: AdminOrderRow[] = [
  {
    id: "o1",
    orderNumber: "MB-9821",
    customer: "Elena Svensson",
    email: "elena@example.com",
    date: "Jun 14, 2024",
    createdAt: "2024-06-14T10:30:00.000Z",
    status: "Shipped",
    statusRaw: "shipped",
    total: "2,450 SEK",
    currency: "SEK",
    isCod: false,
  },
  {
    id: "o2",
    orderNumber: "MB-9819",
    customer: "Marcus Andersson",
    email: "marcus@example.com",
    date: "Jun 14, 2024",
    createdAt: "2024-06-14T15:45:00.000Z",
    status: "Processing",
    statusRaw: "processing",
    total: "1,120 SEK",
    currency: "SEK",
    isCod: true,
  },
  {
    id: "o3",
    orderNumber: "MB-9815",
    customer: "Sofia Lundin",
    email: "sofia@example.com",
    date: "Jun 13, 2024",
    createdAt: "2024-06-13T09:15:00.000Z",
    status: "Delivered",
    statusRaw: "delivered",
    total: "4,890 SEK",
    currency: "SEK",
    isCod: false,
  },
  {
    id: "o4",
    orderNumber: "MB-9810",
    customer: "Jonas Eriksson",
    email: "jonas@example.com",
    date: "Jun 12, 2024",
    createdAt: "2024-06-12T18:20:00.000Z",
    status: "Paid",
    statusRaw: "paid",
    total: "890 SEK",
    currency: "SEK",
    isCod: false,
  },
];

export const MOCK_ADMIN_PRODUCTS: AdminProductRow[] = [
  {
    id: "p1",
    slug: "sculpt-leggings",
    name: "Sculpt Tight High-Rise",
    description: "High-rise sculpting leggings.",
    status: "Active",
    statusRaw: "active",
    price: "990 SEK",
    basePrice: 990,
    stock: 48,
    lowStockThreshold: 5,
    variantCount: 1,
    unitsSold: 12500,
    views: 42000,
    flags: ["Latest Drop", "Best Seller"],
    isLatestDrop: true,
    isPremium: false,
    isBestSeller: true,
    isTemporarilyUnavailable: false,
    categoryId: "33333333-3333-4333-8333-333333330001",
    categorySlug: "leggings",
    categoryName: "Leggings",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAKi6tjJouWa4BgbdkKhv-C3PAMsdW1-LYKU6mJTzdM-kCAbva8AoOix8BibarIzuPEXdxLAa9_Mb8PideBUgKfk-REhTv1hu2PoXaxovA33HGeiDjvVGgzpcCYEtctDTLJuUFsS4-dpGWLoQl4KwgRAdGJla3gBwQ6xbpzw6XtVEUYKKfm4TY-1LyRrd9qZg2R-ynXifBYAZ8kjfYsX7PMH3T0rNamaKBAawz7LQSrDWLN7mbcvkxGVG-F1b-Kc0bpHvWok_54PVY",
    images: [
      {
        id: "mock-img-p1",
        publicUrl:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuAKi6tjJouWa4BgbdkKhv-C3PAMsdW1-LYKU6mJTzdM-kCAbva8AoOix8BibarIzuPEXdxLAa9_Mb8PideBUgKfk-REhTv1hu2PoXaxovA33HGeiDjvVGgzpcCYEtctDTLJuUFsS4-dpGWLoQl4KwgRAdGJla3gBwQ6xbpzw6XtVEUYKKfm4TY-1LyRrd9qZg2R-ynXifBYAZ8kjfYsX7PMH3T0rNamaKBAawz7LQSrDWLN7mbcvkxGVG-F1b-Kc0bpHvWok_54PVY",
        fileName: "hero.webp",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    modelGlbUrl: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
    modelFileName: "Astronaut.glb",
  },
  {
    id: "p2",
    slug: "zen-flow-bra",
    name: "AeroFlow Crop Top",
    description: "Lightweight crop top.",
    status: "Active",
    statusRaw: "active",
    price: "650 SEK",
    basePrice: 650,
    stock: 12,
    lowStockThreshold: 15,
    variantCount: 1,
    unitsSold: 8200,
    views: 31000,
    flags: ["Premium"],
    isLatestDrop: false,
    isPremium: true,
    isBestSeller: false,
    isTemporarilyUnavailable: false,
    categoryId: "33333333-3333-4333-8333-333333330002",
    categorySlug: "sports-bras",
    categoryName: "Sports Bras",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuD8IePc5I5R2_kAa9EYUfRT5uQnYkfOU1VbgeJv5SNOEfv7Ev5UeGDiLJfJawpZw2wem5aCxGecYeFiFB57fVUMpUqEoBj3a_bPcdSjeDG-XEk5KqCaAF0xcC97xjr5HTwnRwweLuUvyxp-oz-k6P9CRV3WZD_o5Qh721y1skhaLIherjDv2Lb2yL9XkZxNJqhbaSYkfuIJPUFkf77oUWvqX8gV-zWBIdPV5R4ywk-Uuyr1xwAL83bkEnmwGgg_wPWJxjscp85W4fI",
    images: [
      {
        id: "mock-img-p2",
        publicUrl:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuD8IePc5I5R2_kAa9EYUfRT5uQnYkfOU1VbgeJv5SNOEfv7Ev5UeGDiLJfJawpZw2wem5aCxGecYeFiFB57fVUMpUqEoBj3a_bPcdSjeDG-XEk5KqCaAF0xcC97xjr5HTwnRwweLuUvyxp-oz-k6P9CRV3WZD_o5Qh721y1skhaLIherjDv2Lb2yL9XkZxNJqhbaSYkfuIJPUFkf77oUWvqX8gV-zWBIdPV5R4ywk-Uuyr1xwAL83bkEnmwGgg_wPWJxjscp85W4fI",
        fileName: "hero.webp",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    modelGlbUrl: null,
    modelFileName: null,
  },
  {
    id: "p3",
    slug: "elite-bra",
    name: "Element Shield Shell",
    description: null,
    status: "Active",
    statusRaw: "active",
    price: "1,290 SEK",
    basePrice: 1290,
    stock: 0,
    lowStockThreshold: 5,
    variantCount: 1,
    unitsSold: 4100,
    views: 18500,
    flags: ["Limited"],
    isLatestDrop: false,
    isPremium: false,
    isBestSeller: false,
    isTemporarilyUnavailable: true,
    categoryId: "33333333-3333-4333-8333-333333330002",
    categorySlug: "sports-bras",
    categoryName: "Sports Bras",
    imageUrl: null,
    images: [],
    modelGlbUrl: null,
    modelFileName: null,
  },
];

export const MOCK_ADMIN_CUSTOMERS: AdminCustomerRow[] = [
  {
    id: "c1",
    name: "Elena Svensson",
    email: "elena@example.com",
    role: "customer",
    locale: "sv",
    currency: "SEK",
    joined: "May 2, 2024",
  },
  {
    id: "c2",
    name: "Marcus Andersson",
    email: "marcus@example.com",
    role: "customer",
    locale: "en",
    currency: "SEK",
    joined: "May 18, 2024",
  },
  {
    id: "c3",
    name: "Admin User",
    email: "admin@mbody.com",
    role: "admin",
    locale: "en",
    currency: "SEK",
    joined: "Apr 1, 2024",
  },
];
