import type { AdminOrderDetail } from "./list-types";
import { MOCK_ADMIN_ORDERS } from "./mock-list-data";
import { EMPTY_ORDER_SHIPPING } from "./orders/shipping/types";

const MOCK_ORDER_DETAILS: Record<string, AdminOrderDetail> = {
  o1: {
    id: "o1",
    orderNumber: "MB-9821",
    customer: "Elena Svensson",
    email: "elena@example.com",
    date: "Jun 14, 2024",
    status: "Shipped",
    statusRaw: "shipped",
    currency: "SEK",
    isCod: false,
    subtotal: "2,200 SEK",
    discountTotal: "0 SEK",
    shippingTotal: "0 SEK",
    taxTotal: "250 SEK",
    grandTotal: "2,450 SEK",
    paymentMethod: "Card",
    paymentStatus: "Succeeded",
    shippingAddressLines: [
      "Elena Svensson",
      "Södermalmstorg 4",
      "118 64 Stockholm",
      "Sweden",
    ],
    shipping: {
      carrier: "postnord",
      carrierLabel: "PostNord",
      service: "standard",
      serviceLabel: "Standard",
      trackingNumber: "PNMB9821DEMO01",
      trackingUrl:
        "https://www.postnord.se/en/our-tools/track-and-trace?shipmentId=PNMB9821DEMO01",
      labelUrl: "/admin/orders/o1/label",
      labelStatus: "generated",
      labelStatusLabel: "Label generated",
      shippedAt: "Jun 14, 2024",
      notes: "Carrier ref: postnord-sim-PNMB9821DEMO01",
    },
    items: [
      {
        id: "oi1",
        productName: "Sculpt Tight High-Rise",
        sku: "SCULPT-LEG-S-BLK",
        sizeCode: "S",
        colorCode: "BLK",
        quantity: 1,
        unitPrice: "990 SEK",
        lineTotal: "990 SEK",
      },
      {
        id: "oi2",
        productName: "AeroFlow Crop Top",
        sku: "AERO-CROP-M-GRY",
        sizeCode: "M",
        colorCode: "GRY",
        quantity: 2,
        unitPrice: "605 SEK",
        lineTotal: "1,210 SEK",
      },
    ],
    returns: [],
    source: "mock",
  },
  o2: {
    id: "o2",
    orderNumber: "MB-9819",
    customer: "Marcus Andersson",
    email: "marcus@example.com",
    date: "Jun 14, 2024",
    status: "Processing",
    statusRaw: "processing",
    currency: "SEK",
    isCod: true,
    subtotal: "990 SEK",
    discountTotal: "0 SEK",
    shippingTotal: "0 SEK",
    taxTotal: "130 SEK",
    grandTotal: "1,120 SEK",
    paymentMethod: "Cash on delivery",
    paymentStatus: "Pending",
    shippingAddressLines: [
      "Marcus Andersson",
      "Drottninggatan 12",
      "111 51 Stockholm",
      "Sweden",
    ],
    shipping: EMPTY_ORDER_SHIPPING,
    items: [
      {
        id: "oi3",
        productName: "Sculpt Tight High-Rise",
        sku: "SCULPT-LEG-M-BLK",
        sizeCode: "M",
        colorCode: "BLK",
        quantity: 1,
        unitPrice: "990 SEK",
        lineTotal: "990 SEK",
      },
    ],
    returns: [],
    source: "mock",
  },
  o3: {
    id: "o3",
    orderNumber: "MB-9815",
    customer: "Sofia Lundin",
    email: "sofia@example.com",
    date: "Jun 13, 2024",
    status: "Delivered",
    statusRaw: "delivered",
    currency: "SEK",
    isCod: false,
    subtotal: "4,390 SEK",
    discountTotal: "0 SEK",
    shippingTotal: "0 SEK",
    taxTotal: "500 SEK",
    grandTotal: "4,890 SEK",
    paymentMethod: "Klarna",
    paymentStatus: "Succeeded",
    shippingAddressLines: [
      "Sofia Lundin",
      "Kungsgatan 8",
      "411 19 Göteborg",
      "Sweden",
    ],
    shipping: {
      carrier: "dhl",
      carrierLabel: "DHL",
      service: "express",
      serviceLabel: "Express",
      trackingNumber: "JDMB9815MANUAL",
      trackingUrl: "https://www.dhl.com/se-en/home/tracking.html?tracking-id=JDMB9815MANUAL",
      labelUrl: null,
      labelStatus: "manual",
      labelStatusLabel: "Manual tracking",
      shippedAt: "Jun 13, 2024",
      notes: null,
    },
    items: [
      {
        id: "oi4",
        productName: "Element Shield Shell",
        sku: "ELEM-SHELL-L-BLK",
        sizeCode: "L",
        colorCode: "BLK",
        quantity: 1,
        unitPrice: "1,290 SEK",
        lineTotal: "1,290 SEK",
      },
      {
        id: "oi5",
        productName: "Sculpt Tight High-Rise",
        sku: "SCULPT-LEG-S-BLK",
        sizeCode: "S",
        colorCode: "BLK",
        quantity: 2,
        unitPrice: "990 SEK",
        lineTotal: "1,980 SEK",
      },
      {
        id: "oi6",
        productName: "AeroFlow Crop Top",
        sku: "AERO-CROP-S-GRY",
        sizeCode: "S",
        colorCode: "GRY",
        quantity: 2,
        unitPrice: "560 SEK",
        lineTotal: "1,120 SEK",
      },
    ],
    returns: [
      {
        id: "ret-o3-1",
        orderItemId: "oi5",
        variantId: "mock-variant-oi5",
        quantity: 1,
        reason: "Size exchange requested",
        status: "approved",
        statusLabel: "Approved",
        createdAt: "Jun 15, 2024",
        approvedAt: "Jun 16, 2024",
        restockedAt: "Jun 16, 2024",
      },
    ],
    source: "mock",
  },
  o4: {
    id: "o4",
    orderNumber: "MB-9810",
    customer: "Jonas Eriksson",
    email: "jonas@example.com",
    date: "Jun 12, 2024",
    status: "Paid",
    statusRaw: "paid",
    currency: "SEK",
    isCod: false,
    subtotal: "790 SEK",
    discountTotal: "0 SEK",
    shippingTotal: "0 SEK",
    taxTotal: "100 SEK",
    grandTotal: "890 SEK",
    paymentMethod: "Apple Pay",
    paymentStatus: "Succeeded",
    shippingAddressLines: [
      "Jonas Eriksson",
      "Storgatan 3",
      "903 26 Umeå",
      "Sweden",
    ],
    shipping: EMPTY_ORDER_SHIPPING,
    items: [
      {
        id: "oi7",
        productName: "AeroFlow Crop Top",
        sku: "AERO-CROP-M-GRY",
        sizeCode: "M",
        colorCode: "GRY",
        quantity: 1,
        unitPrice: "790 SEK",
        lineTotal: "790 SEK",
      },
    ],
    returns: [],
    source: "mock",
  },
};

function buildFallbackMockDetail(orderId: string): AdminOrderDetail | null {
  const row = MOCK_ADMIN_ORDERS.find((order) => order.id === orderId);
  if (!row) return null;

  return {
    id: row.id,
    orderNumber: row.orderNumber,
    customer: row.customer,
    email: row.email,
    date: row.date,
    status: row.status,
    statusRaw: row.statusRaw,
    currency: row.currency,
    isCod: row.isCod,
    subtotal: row.total,
    discountTotal: "0 SEK",
    shippingTotal: "0 SEK",
    taxTotal: "—",
    grandTotal: row.total,
    paymentMethod: row.isCod ? "Cash on delivery" : "Card",
    paymentStatus: row.isCod ? "Pending" : "Succeeded",
    shippingAddressLines: [row.customer, "—"],
    shipping: EMPTY_ORDER_SHIPPING,
    items: [],
    returns: [],
    source: "mock",
  };
}

export function getMockAdminOrderDetail(orderId: string): AdminOrderDetail | null {
  return MOCK_ORDER_DETAILS[orderId] ?? buildFallbackMockDetail(orderId);
}
